export default function HelpCube({num1,close}){
    return (
        <div className="Help">
            <div className='cancel'><button className='cancel-btn' onClick = {close}>X</button></div>
            <div className="center" style={{width:'90%'}}>{num1 === 1 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{1*1*1}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 1 x 1 x 1 = <span className="absolute"><span className="hide">0</span>{1*1*1}</span></div>}</div>
            <div className="center" style={{width:'90%'}}>{num1 === 2 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{2*2*2}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{2} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 2 x 2 x 2 = <span className="absolute"><span className="hide">0</span>{2*2*2}</span></div>}</div>
            <div className="center" style={{width:'90%'}}>{num1 === 3 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{3*3*3}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{3} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 3 x 3 x 3 = <span className="absolute"><span className="hide">0</span>{3*3*3}</span></div>}</div>
            <div className="center" style={{width:'90%'}}>{num1 === 4 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{4*4*4}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{4} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 4 x 4 x 4 = <span className="absolute"><span className="hide">0</span>{4*4*4}</span></div>}</div>
            <div className="center" style={{width:'90%'}}>{num1 === 5 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{5*5*5}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{5} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 5 x 5 x 5 = <span className="absolute"><span className="hide">0</span>{5*5*5}</span></div>}</div>
            <div className="center" style={{width:'90%'}}>{num1 === 6 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{6*6*6}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{6} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 6 x 6 x 6 = <span className="absolute"><span className="hide">0</span>{6*6*6}</span></div>}</div>
            <div className="center" style={{width:'90%'}}>{num1 === 7 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{7*7*7}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{7} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 7 x 7 x 7 = <span className="absolute"><span className="hide">0</span>{7*7*7}</span></div>}</div>
            <div className="center" style={{width:'90%'}}>{num1 === 8 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{8*8*8}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{8} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 8 x 8 x 8 = <span className="absolute"><span className="hide">0</span>{8*8*8}</span></div>}</div>
            <div className="center" style={{width:'90%'}}>{num1 === 9 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{9*9*9}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{9} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 9 x 9 x 9 = <span className="absolute"><span className="hide">0</span>{9*9*9}</span></div>}</div>
            <div className="center" style={{width:'85%'}}>{num1 === 10 ? <div className="Green" style={{fontSize: "30px", paddingBottom: '3px', position:"relative"}}>{num1} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= {num1} x {num1} x {num1} =<span className="absolute"><span className="hide">0</span>{10*10*10}</span></div>:<div style={{fontSize: "30px", paddingBottom: '3px', position: 'relative'}}>{10} <span style={{fontSize:'20px',position:'relative',left:'-5px', top:"-13px"}}>3</span>= 10 x 10 x 10 = <span className="absolute"><span className="hide">0</span>{10*10*10}</span></div>}</div>
        </div>
    )
}